//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManHinhChinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThueSach
    {
        public int MaKhachHang { get; set; }
        public int MaSach { get; set; }
        public Nullable<System.DateTime> NgayThue { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string TinhTrang { get; set; }
    }
}
